[package]
name = "rusticord-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
rusticord-domain = { path= "../domain"}
rusticord-state = { path= "../state"}
rusticord-ui-kit = { path= "../ui-kit"}
rgb = "0.8.53"
gpui.workspace = true

[lints]
workspace = true
