[package]
name = "rusticord-app"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
rusticord-domain = { path= "../domain"}
rusticord-state = { path= "../state"}

[lints]
workspace = true
