[package]
name = "rusticord"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[[bin]]
name = "rusticord"
path = "src/main.rs"

[dependencies]
gpui-kit.workspace = true
rusticord-platform = { path = "../platform", version = "0.1.0" }
rusticord-ui = { path = "../ui", version = "0.1.0" }
